# Generated by Django 5.2.1 on 2025-06-14 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Billeteras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro', verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha de modificación del registro', verbose_name='Fecha de modificación')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el registro', null=True, verbose_name='Notas')),
                ('visible', models.BooleanField(default=True, help_text='Indica si el registro es visible', verbose_name='Visible')),
                ('usuario', models.OneToOneField(help_text='Usuario propietario de la billetera', on_delete=django.db.models.deletion.PROTECT, parent_link=True, related_name='billetera', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('nombre', models.CharField(help_text='Nombre de la billetera', max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la billetera', null=True, verbose_name='Descripción')),
                ('usuario_creacion', models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de creación')),
                ('usuario_modificacion', models.ForeignKey(blank=True, help_text='Usuario que modificó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de modificación')),
            ],
            options={
                'verbose_name': 'Billetera',
                'verbose_name_plural': 'Billeteras',
            },
        ),
        migrations.CreateModel(
            name='FormasPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro', verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha de modificación del registro', verbose_name='Fecha de modificación')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el registro', null=True, verbose_name='Notas')),
                ('visible', models.BooleanField(default=True, help_text='Indica si el registro es visible', verbose_name='Visible')),
                ('nombre', models.CharField(help_text='Nombre de la forma de pago', max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la forma de pago', null=True, verbose_name='Descripción')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo disponible en la forma de pago', max_digits=10, verbose_name='Saldo')),
                ('billetera', models.ForeignKey(help_text='Billetera asociada a la forma de pago', on_delete=django.db.models.deletion.PROTECT, related_name='formas_pago', to='billeteras.billeteras', verbose_name='Billetera')),
                ('usuario_creacion', models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de creación')),
                ('usuario_modificacion', models.ForeignKey(blank=True, help_text='Usuario que modificó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de modificación')),
            ],
            options={
                'verbose_name': 'Forma de Pago',
                'verbose_name_plural': 'Formas de Pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro', verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha de modificación del registro', verbose_name='Fecha de modificación')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el registro', null=True, verbose_name='Notas')),
                ('visible', models.BooleanField(default=True, help_text='Indica si el registro es visible', verbose_name='Visible')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto de la transacción', max_digits=10, verbose_name='Monto')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la transacción', null=True, verbose_name='Descripción')),
                ('fecha_movimiento', models.DateField(auto_now_add=True, help_text='Fecha y hora de la transacción', verbose_name='Fecha')),
                ('tipo', models.CharField(choices=[('I', 'Ingreso'), ('G', 'Gasto')], help_text='Tipo de transacción', max_length=3, verbose_name='Tipo')),
                ('forma_pago', models.ForeignKey(help_text='Forma de pago utilizada en la transacción', on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='billeteras.formaspago', verbose_name='Forma de Pago')),
                ('usuario_creacion', models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de creación')),
                ('usuario_modificacion', models.ForeignKey(blank=True, help_text='Usuario que modificó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de modificación')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
            },
        ),
    ]
